### ISSUE TITLE
Not supported by Jellyfin 

### ISSUE THREAD

**Issue by jorgeJ23** [Kevinjil/Jellyfin.Xtream#108]
Hi,

Thanks for your work @Kevinjil

Since the update, Jellyfin doesn't support any version of Xtream. It updated by itself but next to status it is marked as Status: NotSupported.

Thanks in advance.

**Comment by well-actulily** [comment]
Can confirm, I am also seeing this issue on Jellyfin 10.8.13 running on Windows. Jellyfin Xtream auto-updated when I restarted my server.

**Comment by Kevinjil** [comment]
The versions starting from [v0.6.2](https://github.com/Kevinjil/Jellyfin.Xtream/releases/tag/v0.6.2) require Jellyfin 10.9. I [forgot to update](https://github.com/Kevinjil/Jellyfin.Xtream/commit/af2fc483e07f20aadb5bba7f0017709da78d374d) the target ABI in the `build.yaml`. Downgrading to v0.6.1 and disabling auto-update should work, but I'd recommend updating Jellyfin to 10.9 anyway ;)
