### ISSUE TITLE
xtream series/video on demand, no transcoding

### ISSUE THREAD

**Issue by WilmeRWubS** [Kevinjil/Jellyfin.Xtream#113]
Would it be possible for me to configure so it works by getting the link and streaming it directly?

Tried with windows app, android and android tv and different players and nothing seemed to work. normal live tv does work.
Thanks for any help, sorry if I'm a noob I just cant figure it out. 

Thanks a lot for the plugin.

**Comment by Kevinjil** [comment]
The choice whether or not transcoding is necessary is made by the client+server, not by this plugin.
