### ISSUE TITLE
Plugin Status "Not Supported" on JF10.8.10

### ISSUE THREAD

**Issue by jamesarbrown** [Kevinjil/Jellyfin.Xtream#118]
Hi,

Can you confirm this is right / there is a quick fix / or its a breaking change?

Thanks
James

**Comment by Kevinjil** [comment]
I made a mistake, which has been noted in #108 (https://github.com/Kevinjil/Jellyfin.Xtream/issues/108#issuecomment-2129792322)

**Comment by jamesarbrown** [comment]
Hi, looking at that it says to upgrade to JF10.9 but I am already on JF10.10
