### ISSUE TITLE
Can't switch accounts. cached list

### ISSUE THREAD

**Issue by ashipaek0** [Kevinjil/Jellyfin.Xtream#12]
When i enter in an account A login it works ok.

but when i delete account A login details and enter Account B

the channels from account A remain in the GUI.  

the only way to remove them is to uninstall the plugin

**Comment by Kevinjil** [comment]
Currently cache time is everywhere at most 10 minutes, should not be that big of a problem.

**Comment by Kevinjil** [comment]
Jellyfin has more caching than I expected
