### ISSUE TITLE
Missing VOD and TV Series on new Jellyfin Server

### ISSUE THREAD

**Issue by leungchriscanada** [Kevinjil/Jellyfin.Xtream#123]
I am able to add my Xtream credentials and load Live TV, VOD and TV Series and select which ones I want but I cannot figure out/find the VOD and TV Series tab to load those streams. I am running a Jellyfin 10.9.9 and Xtream 0.6.3.0 and they are both fresh installs.  
<img width="1297" alt="Screenshot 2024-08-14 at 6 07 05 PM" src="https://github.com/user-attachments/assets/daf670b4-8317-4942-9025-122f28283a2c">
<img width="1287" alt="Screenshot 2024-08-14 at 6 07 57 PM" src="https://github.com/user-attachments/assets/1828df0c-7c67-438c-add9-d485f2c3052f">

**Comment by betov69** [comment]
I have the same problem,

**Comment by neotwix** [comment]
Same issue from my side.

**Comment by neotwix** [comment]
How can I help on this issue?

**Comment by emmanuelrobles** [comment]
Same issue here

**Comment by Kevinjil** [comment]
Have you checked the `Show this channel to users` checkbox on the configuration page of VOD and Series? It might take some time before that setting gets propagated to users, as Jellyfin seems to cache it somewhere.

**Comment by emmanuelrobles** [comment]
ive been looking for that option and i cant find it

**Comment by Kevinjil** [comment]
This checkbox does not show to you?
https://github.com/Kevinjil/Jellyfin.Xtream/blob/6faf4a778a11c4ad429c361867874398015abca6/Jellyfin.Xtream/Configuration/Web/XtreamVod.html#L9

**Comment by emmanuelrobles** [comment]
ohh, i see the issue, you need to zoom out, its behind a banner

![image](https://github.com/user-attachments/assets/09f9608a-580f-49b8-b286-9553583b7f7f)


this is how it looks by default

![image](https://github.com/user-attachments/assets/abe75512-4fd8-40d5-9f54-2241c2ab6d91)

**Comment by Kevinjil** [comment]
I've not seen that weird formatting before. What Jellyfin server version, client, and client version are you using to configure it?

**Comment by emmanuelrobles** [comment]
this is a fresh install on truenas, version 10.9.11

**Comment by emmanuelrobles** [comment]
From web browser, FF 131.0.2 (64-bit) Linux

**Comment by Kevinjil** [comment]
Also using FF 131.0.2 (64-bit) on Linux:
![image](https://github.com/user-attachments/assets/b0768cc5-ed28-4a0d-b9b5-e89f371ce74a)

Have you tried incognito with all FF extensions disabled?

**Comment by emmanuelrobles** [comment]
yep, same issue

**Comment by iPhilBln** [comment]
![image](https://github.com/user-attachments/assets/241df7ba-1270-46d3-b93c-17e3e3929be9)
same issue here on :
* Browser: Safari 18.0.1
* Jellyfin: 10.10.1
* XTREAM: 0.6.3.0

**Comment by ratgen** [comment]
Hi, the artifacting of showing two bars on the top was fixed for me by updating the Jellyfin.Model and Jellyfin.Controller dependencies to the latest versions, as done in #138 and #137. This revealed the buttons for showing the channels for series and VOD.

**Comment by Kevinjil** [comment]
The fix has been fixed in #107, but was never released because I forgot to create an actual release afterwards.
