### ISSUE TITLE
[REQUEST] Better channel customization

### ISSUE THREAD

**Issue by eqpaisley** [Kevinjil/Jellyfin.Xtream#13]
Wish list for channels:

- renumber/reorder channels and groups
- change logos
- assign a EPG guide NOT provided by Xtream (one that is added in the live tv interface?)
- add custom "dummy" guide data for when no guide data is available

**Comment by Kevinjil** [comment]
Could you explain the last bullet point?

**Comment by eqpaisley** [comment]
> Could you explain the last bullet point?

When there's no good/accurate EPG information for a channel (PPV, UFC Network, etc) a small text box where the user can enter their own string of text would be helpful then the guide could display "fake" guide data using that text.  So the guide for that channel would automatically populate with fake data using the text entered as the program information.

**Comment by Kevinjil** [comment]
So basically just a text field, and the EPG is filled everyday with 1 event from `00:00` to `23:59` with the entered text?

**Comment by eqpaisley** [comment]
Yes, but it's better to make it in 2-4 hour blocks and not a 24 hour block.  a 2 hour block shows up on your screen when you load the EPG, but a 24 hour block stretches out so long, it might not appear on your screen without side scrolling.  Xteve offers you the choice of a 1,2,3,4 hour block for your 'fake' data.  You don't need to go that far but 1, 2, or 3 hours is a good choice.

**Comment by eqpaisley** [comment]
After continual use, the ability to re-order and renumber channels seems like a must have.

**Comment by Kevinjil** [comment]
I have been working on it on branch [feature/issue-13](https://github.com/Kevinjil/Jellyfin.Xtream/tree/feature/issue-13), just haven't had time to finish it due to more important deadlines.

**Comment by Kevinjil** [comment]
Except for EPG, this has been implemented in #44
