### ISSUE TITLE
Movie metadata

### ISSUE THREAD

**Issue by mrklarth** [Kevinjil/Jellyfin.Xtream#130]
Not sure if this is a limitation of Jellyfin or could even be implemented, but it would be nice if VOD movies had metadata available similar to content in traditional Jellyfin libraries.

**Comment by Kevinjil** [comment]
This would indeed be nice to have, although we have nothing exposed in the API that properly links to a movie. Closing as not feasible.

**Comment by Kevinjil** [comment]
Actually, I have implemented a way with #153
