### ISSUE TITLE
[BUG] Plugin isn't closing LiveTV sessions 

### ISSUE THREAD

**Issue by eqpaisley** [Kevinjil/Jellyfin.Xtream#16]
JF 10.8
Plugin 0.2.1.0
Windows 10 

On my Dashboard, a LiveTV session started 2 days ago appears to still be active.  The activity log has it stopping and starting repeatedly over and over again.  I close the window playing the TV stream 2 mins after is started, but it still shows as active.  It says it's transcoding but there is nothing in my transcode directory.

Dashboard activity (notice the time, which continues to tick up)

![image](https://user-images.githubusercontent.com/5481431/175121520-d71571a2-7abd-464c-9e60-42d9a7ef4002.png)

Activity log (notice how it keeps stopping and restarting - this is happening without me interacting at all.

- [ ] JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 3:30 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 3:25 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 3:20 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 3:15 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 3:10 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 3:05 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 3:00 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 2:55 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 2:50 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 2:45 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 2:40 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 2:35 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 2:30 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 2:25 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 2:20 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 2:15 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 2:10 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 2:05 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 2:00 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 1:55 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 1:50 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 1:45 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 1:40 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 1:35 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 1:30 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 1:25 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 1:20 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 1:15 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 1:10 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 1:05 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 1:00 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 12:54 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 12:49 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 12:44 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 12:39 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 12:34 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 12:29 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 12:24 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 12:19 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 12:14 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 12:09 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 12:04 PM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 11:59 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 11:54 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 11:49 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 11:44 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 11:39 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 11:34 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 11:29 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 11:24 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 11:19 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 11:14 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 11:09 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 11:04 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 10:59 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 10:54 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 10:49 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 10:44 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 10:39 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 10:34 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 10:29 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 10:24 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 10:19 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 10:14 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 10:09 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 10:04 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 9:59 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 9:54 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 9:49 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 9:44 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 9:39 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 9:34 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 9:29 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 9:24 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 9:19 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 9:14 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 9:09 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 9:04 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 8:59 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 8:54 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 8:49 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 8:44 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 8:39 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 8:34 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 8:29 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 8:24 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 8:19 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 8:14 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 8:09 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 8:04 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 7:59 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 7:54 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 7:48 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 7:43 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 7:38 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 7:33 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 7:28 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 7:23 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 7:18 AM
JellyfinUser has finished playing USA Starz Encore East on Firefox
today at 7:13 AM

**Comment by Kevinjil** [comment]
This should already be fixed by https://github.com/Kevinjil/Jellyfin.Xtream/commit/de4a321b711db2a0377c8d477227b7c28948f95f.

Could you re-evaluate after the next release?

**Comment by eqpaisley** [comment]
Will do, ty

**Comment by Kevinjil** [comment]
Release [v0.4.0](https://github.com/Kevinjil/Jellyfin.Xtream/releases/tag/v0.4.0) should solve issues with closing restreams. Please re-open if the issue persists.

**Comment by MonkeySaint** [comment]
I would like this to be reopened as I am having this issue
JF 10.8.13
Plugin 0.6.1.0
