### ISSUE TITLE
[Question] Catch UP / Rewind? 

### ISSUE THREAD

**Issue by CyberPoison** [Kevinjil/Jellyfin.Xtream#17]
Hello does this plugin allow me to rewind like 7 Days back if my provider allow me 7 Days for e.g?

Or is there a planed feature for that?

Other question this plugin works for emby?

**Comment by Kevinjil** [comment]
I discovered the API for that today, and it's on my TODO list.

**Comment by Kevinjil** [comment]
I do not expect it to work with emby, but feel free to try it.

**Comment by CyberPoison** [comment]
I will test on my kubernetes dev stack your plugin on my emby and i will let some info here, 😉 crossing fingers 🤞then that works on emby.

Emby have more apps in terms of devices than emby but they are restricting some kind of features so now i can find many jellyfin plugin, i just hope than this one will work on emby.
So. Impacient to be tomorrow to test 😉

One more thing, do you have so way to DM you?

I'm looking for the xtream UI panel for my iptv source to manage all of them at once i have a Moi Pro AMD server with 16 Tunners and optical fiber setup from sat to grab channels, haters will say ten it's for selling but I'm just using it for my family and to enjoy my weekend on it.
My question is where can i find here on github a xtream code UI null3d or clone code, i will give you an access to my server as free m3u or by api if you want for your tests and devs actually i have around 4000Channels, wich is from exchanges on web all local sourcing home / datacenters like that one in malga (Spain).

Thanks for developing floss plugins dude 😉❤️

**Comment by CyberPoison** [comment]
After draging and drop on the plugins folder on the emby main folder, i could not find anywhere the plugin unfortunately .

Do you have any suggestion on how i should install it ?

**Comment by Kevinjil** [comment]
Did you extract the archive? Other than that I do not know. I do not know how Emby differs in plugin parsing and I do not plan to install Emby / actively support Emby.

**Comment by CyberPoison** [comment]
Yes i have extracted the zip and them moved to plugins folder. 😢 unfortunately the plugin doesn't work for now in emby.

**Comment by NicolaiVdS** [comment]
does this work in jellyfin ? cuz i cant seem to find any catch up section or go back in the EPG
