### ISSUE TITLE
[Feature Request] User control over visibility of libraries, groups, channels

### ISSUE THREAD

**Issue by eqpaisley** [Kevinjil/Jellyfin.Xtream#4]
Jellyfin Ubuntu 20 server
Xtream plugin v 0.1.0.0

- After Xtream credentials are entered, it would ne nice to be able to select which libraries (VOD, Series, Live TV) we would like to display on our server.  
- After selecting which libraries we would like to display, it would be nice to be able to turn groups ON and OFF.  Many providers give users thousands of channels and groups they will never watch
- After paring down groups, it would be nice to hide certain channels within a group.

**Comment by Kevinjil** [comment]
Partially implemented for Live TV by #8.

**Comment by Kevinjil** [comment]
The first bullet point is possible per-user:
1. Open admin dashboard
2. Select users
3. Select user
4. Open `Access` tab
5. Uncheck `Enable access to all channels`
6. Select the channels you want.

Is a server-wide enable/disable necessary?

**Comment by eqpaisley** [comment]
Server wide isn't "necessary" but it would be nice as I don't want to have both Live TV and then Xtream Live available for ANYONE.  Turning it off manually isn't a big deal though!
