### ISSUE TITLE
Assign a EPG guide NOT provided by Xtream

### ISSUE THREAD

**Issue by Kevinjil** [Kevinjil/Jellyfin.Xtream#43]
Originally requested in #13 by @eqpaisley.

**Comment by jensvonbulow** [comment]
Hi,

+1 for this feature please.

I have a channel that does not come with an EPG. I have used WebGrab+Plus to download the EPG. I am able to load the EPG into Jellyfin but I am not able to map the EPG to a channel under the Live TV\TV Guide Data Providers section.

I hope that this is possible and look forward to the implementation.

(Sorry, I don't have the skills to do this myself)

Regards
Jens

**Comment by Kevinjil** [comment]
Not planned, see #124
