### ISSUE TITLE
EPG Time zone adjustment

### ISSUE THREAD

**Issue by butts136** [Kevinjil/Jellyfin.Xtream#45]
Hi, First of all, Thanks you for your amazing plugin :)

It is possible to add an option to change the EPD time zone. 

I mean, all my channel epg are 1 hours late because I can't change the time zone of my shared VPS.

Simple option as +1 hour ou -1 hour would be enough, If possible for sure ;)

Thanks

**Comment by Kevinjil** [comment]
This does not seem like something that should be implemented in this plugin, as it is just a misconfigured Jellyfin installation. What installation method did you use? In most cases it should be possible to configure a timezone for Jellyfin without changing the server timezone.

**Comment by butts136** [comment]
I'm using a Seedbox from Ultra.cc

I can install Jellyfin with a one-click button. Jellyfin is on version 10.8.5

It's running over Linux x86_64 (AMD64)

I can do some SSH command in a terminal but i don't have SUDO permission.

Not sure what you mean by "installation method" :P

Thanks

**Comment by Kevinjil** [comment]
I'm not familiar with that particular hosting provider, a quick search seems to suggest that you can modify environment variables and/or systemd services so that might offer a solution. For further assistance, I think Matrix would be a more suitable location so feel free to hit me up there (same username).

**Comment by mr-glatour** [comment]
Same + 2 hours here, Jellyfin is using the correct date and time, since the events in the logs match the actual times.
