### ISSUE TITLE
Can not play any channel or content

### ISSUE THREAD

**Issue by jpleite** [Kevinjil/Jellyfin.Xtream#58]
Playback Error
This client isn't compatible with the media and the server isn't sending a compatible media format.

the plugin is installed on a synology DS218+ NAS on docker. All movies work just fine. Any idea what might be the issue?

**Comment by Kevinjil** [comment]
What client are you using?

**Comment by jpleite** [comment]
It happens on both iOS app and safari is n macOS

**Comment by Kevinjil** [comment]
- What content are you trying to play?
- Have you enabled transcoding?
- Bonus: could you provide some logs related to the playback attempts

**Comment by jpleite** [comment]
hi @Kevinjil problem solved, my bad. In fact I had the hw transcoding incorrectly set in my synology NAS. Now it is working. Thank you for your excellent work!
