### ISSUE TITLE
No subtitles and media library not visible to other users

### ISSUE THREAD

**Issue by pixelroll** [Kevinjil/Jellyfin.Xtream#60]
Everything is in the title.
Concerning the subtitles, isn't there a way to engrave them or extract them? I don't really know how it works.
And for the users the mediatheques appear only for my main user, strangely enough .
thanks.

**Comment by Kevinjil** [comment]
As far as I know, the Xtream API does not provide any subtitles, so I cannot extract them. Regarding media visibility, make sure you select them under `Channel Access` in the `Access` tab of the user settings.
