### ISSUE TITLE
I have an error putting the url

### ISSUE THREAD

**Issue by DumberSoft** [Kevinjil/Jellyfin.Xtream#61]
I get an error, when I load the channels and choose them, the url they give me hangs and it doesn't work for 20 minutes. Can someone tell me why? 

As you will see in the image, it stays loading and no longer works for 20 minutes.

![Sin título](https://user-images.githubusercontent.com/16725154/228012536-ca94a621-68b6-4ad9-ac3e-7c4335d93035.jpg)

**Comment by Kevinjil** [comment]
Do you have any errors in your browser console?

**Comment by Kevinjil** [comment]
Missing info
