### ISSUE TITLE
Missing items

### ISSUE THREAD

**Issue by TobiasFriberg** [Kevinjil/Jellyfin.Xtream#71]
There a currently a lot of missing content from my list, in series I have 1000+ items in the categories, but only one item when I visit the categories.
<img width="589" alt="Screenshot 2023-08-23 at 15 54 51" src="https://github.com/Kevinjil/Jellyfin.Xtream/assets/5129706/09123ad5-bb61-426f-ba4a-9bfbcfe5f01c">
<img width="468" alt="Screenshot 2023-08-23 at 15 54 33" src="https://github.com/Kevinjil/Jellyfin.Xtream/assets/5129706/4cc2de63-39f8-415c-a3f7-12ad25525b63">

**Comment by ckruijntjens** [comment]
Same issue for me. Even when i  add some genres it never displays in the xtream plugin catagories.

**Comment by Kevinjil** [comment]
Should be solved by #97
