### ISSUE TITLE
Treat Live TV like a Channel

### ISSUE THREAD

**Issue by ashipaek0** [Kevinjil/Jellyfin.Xtream#77]
Feature Request to assign live TV like a Channel under the plugin, so that user access may be selected that way

Logic being that if the Catchup, Series and Movies come from 1 xtream playlist, the other things that don't fall under those sections may be classified as a Live channel.

Currently i can select users that have access to catchup, VOD channels, so maybe its possible to do same with Live TV?

**Comment by Kevinjil** [comment]
This has deliberately been removed in #34 such that we can make proper use of the Live TV functionality of Jellyfin. I would rather suggest more advanced permission control natively baked into Jellyfin than resort to the "Live TV as channel" solution.
