### ISSUE TITLE
Live TV Tuner Setup - How to get LiveTV to show up in JellyFin Client?

### ISSUE THREAD

**Issue by VIPKaiser** [Kevinjil/Jellyfin.Xtream#78]
Live TV Tuner Setup - How to get LiveTV to show up in JellyFin Client?

I've tried "Other" and Detect but nothing is detected. I've set everything up and it shows the VOD stuff but no LiveTV and I missing something?

**Comment by brianjmurrell** [comment]
What did you do to make the Live TV data show up?
