### ISSUE TITLE
anonymous connection

### ISSUE THREAD

**Issue by coccobellof5** [Kevinjil/Jellyfin.Xtream#80]
HI.
Is it possible to add a proxy or openvpn system to the plugin?
IPTV services are not to be trusted, it is better to keep your IP address hidden, and why not, even the user-agent.
Thank you.

**Comment by Kevinjil** [comment]
This is out of the scope considered for the plugin. If you case about privacy, route all traffic generated by the Jellyfin server over a VPN or proxy.
