### ISSUE TITLE
How to use the Plugin after setup ?

### ISSUE THREAD

**Issue by ProTechEx** [Kevinjil/Jellyfin.Xtream#92]
Hey,

I just install and setup the Plugin.
The base URL , Username and Password have been added and saved. Jesllifin has been restartedt.
![image](https://github.com/Kevinjil/Jellyfin.Xtream/assets/5677301/e31ec2ef-6def-4306-9fb5-a8f6bc5ad3f9)

But I can't find it on the Dashboard, what did I forget ?

**Comment by Kevinjil** [comment]
Enable the selection you want on the other configuration tabs.
