### ISSUE TITLE
no configuration tabs on plugin settings page

### ISSUE THREAD

**Issue by idanbnn** [Kevinjil/Jellyfin.Xtream#99]
no configuration tabs on plugin settings page on jellyfin 10.9.1 xtream 0.6.2:
![image](https://github.com/Kevinjil/Jellyfin.Xtream/assets/154705830/bb2ba71e-7c58-4e6d-bf1e-0fd46e1684f1)

**Comment by Kevinjil** [comment]
Known bug in Jellyfin: https://github.com/Kevinjil/Jellyfin.Xtream/pull/96#issuecomment-2110815398 / https://github.com/jellyfin/jellyfin-web/issues/5484

**Comment by Kevinjil** [comment]
Manually navigate to the configuration pages by using the following URLs:

- #/configurationpage?name=XtreamCredentials.html
- #/configurationpage?name=XtreamLive.html
- #/configurationpage?name=XtreamOverrides.html
- #/configurationpage?name=XtreamVod.html
- #/configurationpage?name=XtreamSeries.html

**Comment by idanbnn** [comment]
ohhh nice thank you

**Comment by idanbnn** [comment]
Hi,
they released a fix to this bug in 10.9.2,
but the tabs are still broken,
is it something that you can fix or its still on their end?

when ever you click on a tab it duplicates all the tabs
![image](https://github.com/Kevinjil/Jellyfin.Xtream/assets/154705830/05ff7169-6628-4406-9766-aa087c33cd7d)

when you click again it doesn't show anything but the URL now has a duplicate "web" path
![image](https://github.com/Kevinjil/Jellyfin.Xtream/assets/154705830/eb1d8035-1874-45e8-965e-f6bb003b145c)
